### ISSUE TITLE
split parser out from loader

### ISSUE THREAD

**Issue by sndrs** [deamme/styletron-loader#1]
hello – this loader is really great, so glad to find it!

would you consider splitting out the parser itself from the loader, so that it could be used outside the webpack loader environment?

**Comment by deamme** [comment]
Glad to hear that people find it useful!
You can now use the parser like so:
``` javascript
var parser = require('styletron-loader/parser')

var source = 'CSS_STRING'

var object = parser(source)
```

**Comment by sndrs** [comment]
magic!
